import 'package:flutter/material.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import '../services/payment_service.dart';
import '../services/audit_service.dart';
import '../core/env_config.dart';
import 'dart:developer';

class PaymentProvider with ChangeNotifier {
  final PaymentService _service = PaymentService();
  final AuditService _auditService = AuditService();
  late Razorpay _razorpay;
  bool _isProcessing = false;
  String? _currentBookingId;

  bool get isProcessing => _isProcessing;

  PaymentProvider() {
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  @override
  void dispose() {
    _razorpay.clear();
    super.dispose();
  }

  Future<void> processPayment(String bookingId, double amount, String userName, String userPhone) async {
    _isProcessing = true;
    _currentBookingId = bookingId;
    notifyListeners();
    
    try {
      // 1. Get Razorpay Order ID securely generated by Supabase Edge Function
      final orderId = await _service.createRazorpayOrder(bookingId);
      
      // 2. Open Razorpay checkout
      var options = {
        'key': EnvConfig.razorpayKey,
        'amount': (amount * 100).toInt(), // Amount in minimal unit (paise)
        'name': 'AASHA MEDIX',
        'order_id': orderId,
        'description': 'Payment for Booking #$bookingId',
        'prefill': {
          'contact': userPhone,
          'name': userName,
        },
        'theme': {
          'color': '#2E7D32' // AppColors.primary equivalent
        }
      };

      _razorpay.open(options);
      
    } catch(e) {
      log('Error initiating payment: $e');
      _isProcessing = false;
      notifyListeners();
      // Handle error UI if needed
    }
  }

  void _handlePaymentSuccess(PaymentSuccessResponse response) async {
    log('Payment Success: \${response.paymentId}');
    try {
      if (response.paymentId != null && response.orderId != null && response.signature != null) {
        // Verify payment server-side via Edge Function.
        // The edge function should also update the payment and booking status to 'confirmed'.
        await _service.verifyPayment(
          response.paymentId!, 
          response.orderId!, 
          response.signature!
        );
        await _auditService.logAction(
          action: 'PAYMENT_VERIFIED',
          details: 'Order ID: \${response.orderId}, Payment ID: \${response.paymentId}'
        );
        log('Payment Verified successfully on server.');
      }
    } catch (e) {
      log('Payment Verification Error: $e');
    } finally {
      _isProcessing = false;
      _currentBookingId = null;
      notifyListeners();
    }
  }

  void _handlePaymentError(PaymentFailureResponse response) {
    log('Payment Error: \${response.code} - \${response.message}');
    _isProcessing = false;
    _currentBookingId = null;
    notifyListeners();
    // Notify UI of error
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    log('External Wallet Selected: \${response.walletName}');
    // Often handled simply by letting Razorpay complete the flow, but good for tracking
  }
}
